### ISSUE TITLE
Too slow on Windows

### ISSUE THREAD

**Issue by IgaguriMK** [dnlmlr/cargo-clean-all#1] opened 2022-04-25 12:11 UTC
## Problem

`cargo clean-all` is too slow on Windows.

Up to 37 times slower than `cargo clean-recursive` if there are many files on `target`.

## How to reproduce the problem

Run on PowerShell.

Create test directory.

```
> cargo new clean_sample_project
> cd .\clean_sample_project\
```

Edit `Cargo.toml`

```
[dependencies]
actix-web = "=4.0.1"
```

Run builds and generate files in `target`.

```
> cargo doc; cargo build; cargo build --release
```

Measure `cargo clean-all -y` execution time.

```
> Measure-Command { cargo clean-all -y }
```

`cargo clean-all` takes 463.06 sec and `cargo clean-recursive` takes 12.24 sec in my environments.

## Environments

```
CPU: AMD Ryzen 9 3900X 12-Core Processor 3.79 GHz
OS : Windows 10 Pro 21H2 19044.1645
SSD: WESTERN DIGITAL WD Black SN750 NVMe WDS200T3XHC

rustc 1.58.1 (db9d1b20b 2022-01-20) x86_64-pc-windows-msvc
cargo-clean-all v0.4.0
```

**Comment by dnlmlr** [comment] 2022-04-25 14:50
Thanks for the issue, I didn't necessarily expect anyone to even check this project out and mainly created it for my own needs and to try out publishing on crates.io . 

Anyways, I can reproduce this issue and the problem seems to be that the `std::fs::remove_dir_all` function I used to for deleting the directories is currently extremely slow on windows. Running `cargo clean-all -y` on your suggested test dir took almost 10 minutes for me. No idea how I didn't notice that before.

So to fix this I switched to using the [remove_dir_all](https://crates.io/crates/remove_dir_all) crate which provides an optimized version of the deletion function. With this change I get the following timings using the same steps as you:

| cargo clean-all -y | cargo clean-recursive |
|-------------------|-----------------------|
| 16.240 sec           | 25.682 sec                 |

```
CPU: AMD Ryzen 7 2700X Eight-Core Processor 3.70 GHz
OS: Windows 10 Pro 20H2 19042.1645
SSD: Samsung 970 EVO 500GB

rustc 1.60.0 (7737e0b5c 2022-04-04) x86_64-pc-windows-msvc
cargo-clean-all v0.4.1
cargo-clean-recursive v0.9.5
```

Wrapping this up, the issue should be fixed by 250fd8353ac067dd3489fddb23246d8b55b8fcab which is also included in the latest version `0.4.1` on [crates.io](https://crates.io/crates/cargo-clean-all).

PS: I also removed the claims about performance in comparison to your `cargo-clean-recursive` since those were really unscientific and might change at any point anyways.

**Closed as completed** 2022-05-03 16:32 UTC
