### ISSUE TITLE
Infinite symlink loop during size calculations

### ISSUE THREAD

**Issue by kraktus** [dnlmlr/cargo-clean-all#13] opened 2023-12-11 11:08 UTC
Hey, thanks for the tool!

I tried to run `cargo-clean -i` in the dir containing all the projects I contribute into (~200, mostly *not* rust), and the CLI is hanging forever, trying to scan all the files looking for `target/` directories. Peeking at the code, there seems to be no early return when the dir is not a rust project, which mean it will then recursively scan all dirs (including artefacts! the dreaded `node_modules/` and so on).

This is a supposition, as even with `--verbose` mode I couldn't see where/what it was looking at.

couple of options:
 * Manual maximum `--depth` option. Easy but no super user-friendly
 * Limit to git-tracked files by default, which should avoid scanning all build artefacts.
 * Trying to detect non-rust projects. There's a good list here: https://github.com/stevegrunwell/asimov/blob/a319695e4e351c6fe9623d079bb4d228950fdcb2/asimov#L36 already that could be used to early-return
 * Maybe there's an external lib that does the detection already

**Comment by dnlmlr** [comment] 2023-12-11 12:05
Hi, thanks for the comment. You raise a good point and I think more than one of your suggestions could be implemented together. 

- Adding a depth option is indeed quite easy and can help a lot in certain situations. I'll definitely add that since it is generally helpful.
- Skipping over git ignored directories and files is something I thought about and that is implemented in a few similar projects. This however adds a noticable performance impact compared to simply doing the straight forward scan (at least when working with mainly rust projects). I would suggest that this might be implemented in an opt-in way.
- I think detecting and ignoring at least the black hole that is `node_modules` is something that should be implemented. I'll check if there are more similar directories that can safely be ignored. I don't want to completely skip over non-rust project since those might still contain rust projects for example as dependencies.

As a somewhat related question, is your project dir stored on a hard drive or SSD? One of the key features that make this tool rather fast is the multithreaded directory scan. That works well with SSDs but can decrease performance when targeting HDDs. (This of course doesn't change anything about the issue and is more of a curiosity question)

**Comment by kraktus** [comment] 2023-12-11 12:07
Thanks for the fast and insightful feedback!

I use an SSD, the whole dir is about 150Gb. (Most of which is rust target/)

**Comment by dnlmlr** [comment] 2023-12-16 16:52
Did you figure out if the slowness you experienced was caused by the symlink loop you fixed in #14 ? Or to ask in a different way, is it still slow with that fix applied?

**Comment by kraktus** [comment] 2023-12-16 17:29
Yes, it was slow due to the infinite loop. It still takes about ~20s without it but that’s acceptable.

**Comment by dnlmlr** [comment] 2023-12-16 18:05
I implemented the fix in efdd797b07fef7643503461a289ba8e429d3aa38 and verified that it works with the project you liked in #14 after confirming that I also get the infinite loop with the previous version. 

Feel free to reopen this issue if the fix doesn't work for you for some reason.

Thanks again for bringing this up.

**Closed as completed by dnlmlr** 2023-12-16 18:05 UTC
